int refill_buffer (Bit_stream_struc *);
void empty_buffer (Bit_stream_struc *, int);
void open_bit_stream_w (Bit_stream_struc *, int);
void close_bit_stream_w (Bit_stream_struc *);
void alloc_buffer (Bit_stream_struc *, int);
void desalloc_buffer (Bit_stream_struc *);
void back_track_buffer (Bit_stream_struc *, int);
unsigned int get1bit (Bit_stream_struc *);
void put1bit (Bit_stream_struc *, int);
unsigned long look_ahead (Bit_stream_struc *, int);
unsigned long getbits (Bit_stream_struc *, int);
extern void putbits (Bit_stream_struc *, unsigned int, int);
void byte_ali_putbits (Bit_stream_struc *, unsigned int, int);
unsigned long byte_ali_getbits (Bit_stream_struc *, int);
unsigned long sstell (Bit_stream_struc *);
int end_bs (Bit_stream_struc *);
int seek_sync (Bit_stream_struc *, long, int);
unsigned int hget1bit (void);	/* MI */
unsigned long hgetbits (int);
unsigned long hsstell (void);
void hputbuf (unsigned int, int);
void bs_set_minimum(int minimum);
